name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build server lib and server sample
      run: dotnet build --configuration Release --no-restore
    - name: Test server lib
      run: dotnet test --no-restore --verbosity normal
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build client lib
      run: |
        cd authzyin.js
        npm install
        npm run build
    - name: Build client SPA 
      run: |
        cd authzyin.js/example
        npm install
        npm run build
    
